baseURL = "https://pavolloffay.github.io/"
languageCode = "en-us"
title = "Pavol Loffay"
theme = "light-hugo"
publishDir = "docs"
staticDir = ["static"]
googleAnalytics = "UA-111628265-1"

author = "Pavol Loffay"
copyright = "© Copyright 2018 Pavol Loffay"

[Params]
  description = "Software Engineer"
  email = "p.loffay@gmail.com"
  github = "pavolloffay"
  twitter = "ploffay"
  linkedin = "pavolloffay"
  youtube = "PavolLoffay"
  logo = "images/logo.png"
